# === FILE: site_scout_project/Makefile ===

.PHONY: fmt lint test clean

# ---------------------------------------------------------------------------
# Formatting – Black + Ruff (format mode)
# ---------------------------------------------------------------------------
fmt:
	@echo "→ formatting with black & ruff format"
	black site_scout tests
	ruff format site_scout tests

# ---------------------------------------------------------------------------
# Lint – Ruff (static rules) + mypy (type checking)
# ---------------------------------------------------------------------------
lint:
	@echo "→ ruff check & mypy strict"
	ruff check site_scout tests
	mypy site_scout

# ---------------------------------------------------------------------------
# Unit tests (quiet)
# ---------------------------------------------------------------------------
test:
	pytest -q

# ---------------------------------------------------------------------------
# Clean caches / artefacts generated by tests & build
# ---------------------------------------------------------------------------
clean:
	rm -rf __pycache__ .pytest_cache .mypy_cache *.egg-info
