# configs/default.yaml

# 1. Базовый URL для сканирования
#    Этот URL станет отправной точкой для краулинга сайта.
base_url: "https://example.com"

# 2. Максимальная глубина обхода
#    Определяет, насколько глубоко сканер будет переходить по ссылкам.
max_depth: 2

# 3. Параметры асинхронных HTTP-запросов
timeout: 10.0       # секунды ожидания ответа
rate_limit: 2.0     # запросов в секунду
user_agent: "SiteScoutBot/1.0"
retry_times: 1      # повтор при HTTP 5xx

# 4. Пути к словарям для brute-force сканирования
wordlists:
  paths: "wordlists/paths.txt"
  files: "wordlists/files.txt"

# 5. Настройки локализации (для национальных сегментов)
localization:
  jp:
    subdomain: "jp."
    path_prefix: "/jp"
    hreflangs:
      - ja
      - ja-JP
    accept_languages:
      - ja
      - ja-JP
  kr:
    subdomain: "kr."
    path_prefix: "/kr"
    hreflangs:
      - ko
      - ko-KR
    accept_languages:
      - ko
      - ko-KR
  cn:
    subdomain: "cn."
    path_prefix: "/cn"
    hreflangs:
      - zh
      - zh-CN
    accept_languages:
      - zh
      - zh-CN
