# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
          pip install mypy pytest pytest-cov flake8 black isort pydocstyle bandit radon

      - name: Lint with flake8
        run: |
          flake8 site_scout

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Check import sorting with isort
        run: |
          isort --check-only .

      - name: Check docstrings with pydocstyle
        run: |
          pydocstyle site_scout

      - name: Security scan with Bandit
        run: |
          bandit -r site_scout

      - name: Complexity analysis with Radon
        run: |
          radon cc site_scout -a

      - name: Type-check with mypy
        run: |
          mypy site_scout --strict

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=site_scout --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml